---
title: "Assignment 1: Introduction"
author: "Kendra Sultzer"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Salk_A03_Introduction.Rmd") prior to submission.

The completed exercise is due on <>.

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I've never worked with Git before, so I'm excited to be exploring it!  I did a little R work in undergrad and refreshed my knowledge in statistics last year.  I'm currenty taking another class utilizing R, so I'm hoping to get back into it quickly. I haven't had any formal experience with data analytics, but I've conducted data science projects.  I'm hoping this class will help me streamline that proecess for easier presentation and manipulation in the future!

2. Are there any components of the course about which you feel confident?

> Answer: We had to use RMarkdown a fair bit in my statistics class, so I'm hoping that will be pretty straightforward.  

3. Are there any components of the course about which you feel apprehensive?

> Answer: I'm a bit nervous learning how to use ggplot because I feel like I struggled with that in statistics.  But hoping to feel less apprehensive about it once I learn to do it better. 


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository  and that you have updated your course README file. 

> Answer: https://github.com/sultzerk/Environmental_Data_Analytics_2021.git


